name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: 4985762349857/my-project
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  securitytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Downloading Dependency check tool
        run: wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.2.2/dependency-check-6.2.2-release.zip 
    
      - name: Unzipping archive and installing
        run: unzip dependency-check-6.2.2-release.zip && ls -l && dependency-check/bin/dependency-check.sh -s .

   #   - uses: actions/checkout@v2        
      - name: DevSkim Scan
        uses: microsoft/DevSkim-Action@v1
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: devskim-results.sarif

  #    - uses: actions/checkout@v2
      - name: Trufflehog Actions Scan
        uses: edplato/trufflehog-actions-scan@master

  #    - uses: actions/checkout@v2
      - name: Spot Bugs Scan
        run: wget https://github.com/spotbugs/spotbugs/releases/download/4.3.0/spotbugs-4.3.0.tgz

      - name: Unzip and install
        run: gunzip -c spotbugs-4.3.0.tgz | tar xvf - && SPOTBUGS_HOME/bin/spotbugs && SPOTBUGS_HOME/lib/spotbugs.jar


